title = "Random blog"
baseurl = "http://ramaxlo.github.io/blog"
languageCode = "zh-tw"
copyright = "&copy; Ramax Lo 2016"

[params]

[params.highlight]
style = "github"

[[params.social]]
url = "https://github.com/ramaxlo"
fa_icon = "fa-github"
